export { default as SplashScreenBg } from "./SplashScreen/ChooseLanguage";
export { default as RadioBtns } from "./interface/RadioButtons";
export { default as MenuItems } from "./interface/MenuItems";
// export { default as SplashScreenMenu } from "./SplashScreen/SplashScreenMenu";
// export { default as SplashScreenLogo } from "./SplashScreen/SplashScreenLogo";
// export { default as SplashScreenMockups } from "./SplashScreen/SplashScreenMockups";
// export { default as SplashScreenLang } from "./SplashScreen/SplashScreenLang";
export { default as Category } from "../components/home/Categories/Category";
export { default as Categories } from "../components/home/Categories/Categories";
export { default as MenuCard } from "./menu/MenuCard";
export { default as SearchBar } from "./interface/SearchBar";
export { default as CartContainer } from "./cart/CartContainer";
export { default as CartItem } from "./cart/CartItem";
export { default as ChooseLanguage } from "./SplashScreen/ChooseLanguage";
export { default as ChooseMenu } from "./SplashScreen/ChooseMenu";
